### PR TITLE
MVP of supporting standard bevy font loader

### PR DESCRIPTION
**Pull request by blaind**

### CODE REVIEW

**Comment by Fr33maan** [comment]
Any wish to merge this PR as it would instantly allow us to have both 2d and 3d texts ?

**Comment by Fr33maan** [comment]
Just tried from the `font-loader` branch and it's working like a charm!

image

**Comment by blaind** [comment]
I was mostly concerned of the API change (`font: asset_server.load("fonts/FiraMono-Medium.ttf#mesh")`) where the `#mesh` is always required - would it be confusing to end-users?

Haven't figured an alternative way yet, though, so maybe that could be an acceptable tradeoff.

**Comment by Fr33maan** [comment]
This is the perfect tradeoff, small change in the code, works like a charm with existing Bevy API, no breaking change introduced. You even added a warning message!
I would suggest adding a change to the doc to stop saying that the lib is incompatible with Bevy Text and make it clear that labeling is mandatory. 
While changing the readme, you should update the version number which is in the readme:
```
Add to Cargo.toml:

[dependencies]
bevy_text_mesh = "0.1.0"
```

**Comment by blaind** [comment]
Thank you for the readme note - updated.

I've published a new version to crates.io now, 0.4.0 including this change.

**Pull request merged**
