### PR TITLE
migrated to bevy 0.8

### PR DESCRIPTION
**Pull request by gavlig**
Not much had to be changed. Tested on both examples.

### CODE REVIEW

**Comment by gavlig** [comment]
sorry, i didnt realize new commits will be part of this pr too. Closing it for now

**Comment by blaind** [comment]
No problem! Was the 0.8 upgrade commit https://github.com/blaind/bevy_text_mesh/pull/13/commits/86df002f8b1d74c39e968a9ce42525fda8028325 this one, and no others?

**Comment by gavlig** [comment]
yep, pretty much

**Comment by blaind** [comment]
Ok, thank you. I've now published v0.3.0 that maps to bevy 0.8.0

**Pull request closed without merging**
